# -*- coding: utf-8 -*-
"""label_TrainCatSet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vDyBZ7Ql-8qQ3l7EWJB9TfnwGy66qGGn
"""

import pandas as pd
import os
import numpy as np

# Enlisto los nombres de las imagenes
imagenes = os.listdir('/content/drive/MyDrive/Colab Data/Proyecto buscomiperro/gatos')
imagenes[:5]

def extract_ext(id):  # Para que el resultado sea como el de razas le quito la extensión
    return os.path.splitext(id)[0]

labels = list(map(extract_ext, imagenes))

df = pd.DataFrame()
df['id'] = labels
df['breed'] = 'gato'
df.to_csv('cat_labels.csv')

